apiVersion: v1
kind: ConfigMap
metadata:
  name: accb-otel-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      awscloudwatchlogs:
        log_group_name: /accb/${ENVIRONMENT}/app
        log_stream_name: otel
      awsxray:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [awsxray]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [awscloudwatchlogs]
