apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "accb.name" . }}-replay
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "accb.name" . }}
      containers:
        - name: job
          image: "{{ .Values.image.repository }}-job:{{ .Values.image.tag }}"
