apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: keyvault-secrets
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: accb-dev-aca-dapr-kv
    - name: azureClientId
      value: managed-identity-client-id
scopes:
  - publisher
  - subscriber
