apiVersion: v1
kind: ServiceAccount
metadata:
  name: multi-role-platform
  namespace: accb-gke-platform
  annotations:
    iam.gke.io/gcp-service-account: accb-gke-platform-${ACCB_ENV}@example.iam.gserviceaccount.com
