apiVersion: v1
kind: ServiceAccount
metadata:
  name: multi-role-platform
  namespace: accb-eks-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/accb-eks-platform-${ACCB_ENV}
